### ISSUE TITLE
bug: Invalid steamID create issue in DB

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-VIP-Core#5]
`[ VIP ] VIP-Player Mirai (STEAM_ID_STOP_IGNORING_RETVALS, xxx.xx.xx.xx) (ID: 0) successfully added!`
![image](https://github.com/srcdslab/sm-plugin-VIP-Core/assets/11679883/581e8085-ac36-4bfd-806a-4f9f2cd55fbc)

**Comment by maxime1907** [comment]
also merge it in upstream (only merged it here so you are not blocked)

**Comment by Rushaway** [comment]
It's done, but I don't know why you should maintain upstream since we don't follow it completely
